// SPDX-License-Identifier: MIT

use super::{FrameBuf, FrameLength, Header, HeaderBytes, Reader, HEADER_LEN};
use crate::{
    byte_array,
    error::{Error, ErrorKind},
    key::{ParentKey, ParentKeyId, ParentKeySecret},
};
use std::{
    io::{Cursor, Read, Seek, SeekFrom},
    vec::Vec,
};

// Generated by zymic_core at revision 04eb81f using the v1 HeaderBuilder and
// v1 stream writer. Keeping this as ciphertext prevents the compatibility
// tests from depending on any encoder in the current implementation.
const FIXTURE: &[u8] = include_bytes!("fixtures/multiframe.bin");
const INVOCATION_FIXTURE: &[u8] = include_bytes!("fixtures/invocation.bin");
const PLAINTEXT_LEN: usize = 5000;
const V1_FRAME_LEN: usize = 4096;

fn parent_key() -> ParentKey {
    const ID: ParentKeyId = byte_array![1u8; 16];
    const SECRET: ParentKeySecret = byte_array![2u8; 32];
    ParentKey::new(ID, SECRET)
}

fn plaintext() -> Vec<u8> {
    (0..PLAINTEXT_LEN)
        .map(|index| (index % 251) as u8)
        .collect()
}

fn fixture_parts() -> (Header, &'static [u8]) {
    let header_bytes = HeaderBytes::from(&FIXTURE[..HEADER_LEN]);
    let header = Header::from_bytes(&parent_key(), header_bytes).unwrap();
    (header, &FIXTURE[HEADER_LEN..])
}

fn inner_error(error: &std::io::Error) -> &Error {
    error.get_ref().unwrap().downcast_ref::<Error>().unwrap()
}

#[test]
fn decodes_v1_multiframe_fixture() {
    let (header, frames) = fixture_parts();
    assert_eq!(header.frame_len(), FrameLength::Len4KiB);

    let mut reader = Reader::new(Cursor::new(frames), &header);
    let mut decoded = Vec::new();
    reader.read_to_end(&mut decoded).unwrap();

    assert_eq!(decoded, plaintext());
    assert!(reader.is_eof());
    reader.is_eof_or_err().unwrap();
}

#[test]
fn decodes_v1_frame_with_invocation() {
    let header_bytes = HeaderBytes::from(&INVOCATION_FIXTURE[..HEADER_LEN]);
    let header = Header::from_bytes(&parent_key(), header_bytes).unwrap();
    let frames = &INVOCATION_FIXTURE[HEADER_LEN..];
    let mut reader = Reader::new(Cursor::new(frames), &header);
    let mut decoded = Vec::new();

    reader.read_to_end(&mut decoded).unwrap();

    assert_eq!(decoded, b"v1 invocation compatibility");
    reader.is_eof_or_err().unwrap();
}

#[test]
fn framebuf_decodes_v1_frames() {
    let expected = plaintext();
    let (header, frames) = fixture_parts();
    let mut frame_buf = FrameBuf::new(&header);

    assert_eq!(frame_buf.copy_from_encrypted_bytes(frames), V1_FRAME_LEN);
    assert!(!frame_buf.decrypt(0).unwrap());
    assert_eq!(frame_buf.payload(), &expected[..V1_FRAME_LEN - 32]);

    let end_frame = &frames[V1_FRAME_LEN..];
    assert_eq!(
        frame_buf.copy_from_encrypted_bytes(end_frame),
        end_frame.len()
    );
    assert!(frame_buf.decrypt(1).unwrap());
    assert_eq!(frame_buf.payload(), &expected[V1_FRAME_LEN - 32..]);
}

#[test]
fn framebuf_encoded() {
    let header_bytes = HeaderBytes::from(&INVOCATION_FIXTURE[..HEADER_LEN]);
    let header = Header::from_bytes(&parent_key(), header_bytes).unwrap();
    let encoded_frame = &INVOCATION_FIXTURE[HEADER_LEN..];
    let mut frame_buf = FrameBuf::new(&header);

    frame_buf.chunk_mut()[..encoded_frame.len()].copy_from_slice(encoded_frame);
    frame_buf.commit_chunk_mut(encoded_frame.len()).unwrap();

    assert!(frame_buf.decrypt(0).unwrap());
    assert_eq!(frame_buf.payload(), b"v1 invocation compatibility");
}

#[test]
fn header_parser_only_version_one() {
    let bytes = HeaderBytes::from(&FIXTURE[..HEADER_LEN]);
    Header::from_bytes(&parent_key(), bytes.clone()).unwrap();

    let error = match crate::stream::v2::Header::from_bytes(&parent_key(), bytes) {
        Err(error) => error,
        Ok(_) => panic!("v2 parser accepted a v1 header"),
    };
    assert_eq!(error.kind(), &ErrorKind::UnsupportedVersion(1));
}

#[test]
fn invocation_count_auth() {
    let (header, frames) = fixture_parts();
    let mut tampered = frames.to_vec();

    // The v1 invocation count begins immediately after the sequence number.
    tampered[4] ^= 1;

    let error = Reader::new(Cursor::new(tampered), &header)
        .read_to_end(&mut Vec::new())
        .unwrap_err();
    assert!(matches!(inner_error(&error).kind(), ErrorKind::Cipher(_)));
}

#[test]
fn missing_end_frame() {
    let (header, frames) = fixture_parts();
    let body_frame_only = &frames[..V1_FRAME_LEN];
    let mut reader = Reader::new(Cursor::new(body_frame_only), &header);
    let mut decoded = Vec::new();

    reader.read_to_end(&mut decoded).unwrap();
    assert_eq!(decoded, &plaintext()[..V1_FRAME_LEN - 32]);
    assert_eq!(
        reader.is_eof_or_err().unwrap_err().kind(),
        &ErrorKind::Truncation
    );
}

#[test]
fn truncated_end_frame() {
    let (header, frames) = fixture_parts();
    let truncated = &frames[..frames.len() - 1];

    let error = Reader::new(Cursor::new(truncated), &header)
        .read_to_end(&mut Vec::new())
        .unwrap_err();
    assert!(matches!(
        inner_error(&error).kind(),
        ErrorKind::InvalidEndLength(_)
    ));
}

#[test]
fn seeks_frame_boundaries() {
    let expected = plaintext();
    let (header, frames) = fixture_parts();
    let mut reader = Reader::new(Cursor::new(frames), &header);

    assert_eq!(reader.seek(SeekFrom::Start(4060)).unwrap(), 4060);
    let mut decoded = [0u8; 16];
    reader.read_exact(&mut decoded).unwrap();
    assert_eq!(decoded, expected[4060..4076]);

    assert_eq!(reader.seek(SeekFrom::End(-10)).unwrap(), 4990);
    let mut decoded = Vec::new();
    reader.read_to_end(&mut decoded).unwrap();
    assert_eq!(decoded, expected[4990..]);

    assert_eq!(reader.seek(SeekFrom::End(0)).unwrap(), 5000);
    assert_eq!(reader.read(&mut [0u8; 1]).unwrap(), 0);

    assert_eq!(reader.seek(SeekFrom::Start(5000)).unwrap(), 5000);
    assert_eq!(reader.read(&mut [0u8; 1]).unwrap(), 0);
}
